### ISSUE TITLE
Support passing dynamic args & batch run shortcuts

### ISSUE THREAD

**Issue by jjw24** [mantasjasikenas/flow-launcher-shortcuts-plugin#1]
Hey great plugin.

Wondering if you plan to 
1. Support dynamic args so it would be something like `q add shopping_urls https://www.google.com/search?q={q}`, where user can pass in the arg `q shopping_urls -q something` 
2. Support batch shortcut open operations where you can trigger all shortcuts with the same name or 'group name'.

Reason for this suggestion is I feel this plugin is a suitable one for solving a popular requested [feature](https://github.com/Flow-Launcher/Flow.Launcher/issues/2097) in the WebSearch plugin

**Comment by mantasjasikenas** [comment]
Thank you for your suggestion. 

The latest version, `v1.0.5`, now includes the first version of dynamic argument support. To use dynamic arguments, simply surround the argument name with `${q}` syntax, as you would with a variable. Additionally, you provide dynamic argument value to shortcut using the flag `-arg_name arg_value`.

Furthermore, shortcut groups have been added. You can create, remove, or view groups using the `q group` command. Currently, from within Flow Launcher, you can create groups of existing shortcuts by using their keys. For greater flexibility, you can also edit the shortcut configuration file. An example of a configuration file can be found in the `README.md` file.
