### ISSUE TITLE
skip '-q' for syntax sugar

### ISSUE THREAD

**Issue by anonymousALLDAY** [mantasjasikenas/flow-launcher-shortcuts-plugin#12]
Thanks for great plugin.

I wanna do `search flow launcher` intead of `q search -q "flow launcher"`

skipping plugin keyword can be achievable by setting the keyword as `*` but i also want to skip `-q`.

it would be good if the argument value is assigned to the argument name in url automatically, when there is only one argument.

thanks!

**Comment by mantasjasikenas** [comment]
Thanks for the suggestion.

You can change the plugin keyword to `*` using the `q keyword set *` command. 

Later in the week, I will make the argument name optional if only one argument is available.
