### ISSUE TITLE
Feature Suggestion: Set Application

### ISSUE THREAD

**Issue by proxemics** [mantasjasikenas/flow-launcher-shortcuts-plugin#13]
Is it possible to set a specific application for a file or a URL to open in instead of the default application? I could see it reverting to the default app if there is not one manually specified, but personally would find it very useful to set specific apps for different files or particularly URLS.

Thanks for the great plugin!

**Comment by mantasjasikenas** [comment]
Thank you for providing your feedback.

At this time, there is no option available for setting specific applications. Files and URLs open in default applications. Can you provide more details on how you imagine setting a specific application for a shortcut? Should this be included in the `add` command?

**Comment by proxemics** [comment]
Yeah, I could see that. Perhaps could be appended to the add function and if missing in the command it uses the default app? To be honest, I've been mostly adding mine in the file manually.  I just imagined an optional variable like this in the file (but am def no coding expert or anything haha):

```
{
    "Type": "File",
    "Path": "C:\\Users\\my_user\\Documents\\my_file.txt",
    "Key": "my_file"
    "App": "... App exe path or other way to point to an app",
  },
  {
    "Type": "Url",
    "Path": "www.google.com",
    "Key": "google"
    "App": "... App exe path or other way to point to an app",
  },
```

Not a make-or-break feature or anything, just a thought. In my use cases I prefer some URLs to open in different browsers due to what accounts are logged in across personal and work etc.

Appreciate your work and this plug-in regardless! 🙌
