### ISSUE TITLE
Feature Request: Add Indication of Loading In Progress (to handle files or groups of files that are slow to load)

### ISSUE THREAD

**Issue by EnigmaSolved** [mantasjasikenas/flow-launcher-shortcuts-plugin#14]
Greetings! I am appreciating your plugin, but am running into a curious issue. I am on a new, fast desktop computer with a NVMe M.2 SSD. I have defined a shortcut group comprising of 3 files (two Excel spreadsheets and one Access database), all stored on the SSD. When I execute this group via keyword it can take >10 seconds for anything visually to happen on the screen, which has at times led me to mistakenly interpret that the plugin had not executed my command (and so I hit Enter again, which results in files being opened twice eventually).

I have done some testing the and the delay has nothing to do with the plugin, but rather is the result of the Microsoft Access database being slow to open (and it was originally first in the Group). If I change the Group order so that the Excel files are first then I do see both of them open rapidly (and the Access database follows eventually after).

Since the Shortcuts plugin has no way of knowing how long a file will take to load, it seems it could be helpful if there were some sort of visual indication that the executed command was received (so that the user doesn't just keep hitting Enter, errantly). Or is this perhaps something that would be more appropriate to add to Flow Launcher core? Either way, some kind of UI visual feedback that the command was received might be good (if possible). This is not a pressing need for me since I've changed my Group order so that the faster loading Excel files are first, but it seemed worth posting about this since it might come up for other users at some point.

Thanks for reading and considering my suggestion! :)

**Comment by mantasjasikenas** [comment]
Thanks for reaching out and sharing your experience.

I'll consider your suggestion for visual feedback in future updates. In the meantime, in the `v1.1.5` version, I modified the group shortcut execution. Now it should start in parallel order.

If you still run into issues, let me know.

**Comment by EnigmaSolved** [comment]
`1.1.5` parallel execution works fantastic! Everything opens super-fast, simultaneously now! Thank you much! :)
