### ISSUE TITLE
Feature Request: pull shortcut Icons

### ISSUE THREAD

**Issue by c0deZ3R0** [mantasjasikenas/flow-launcher-shortcuts-plugin#15]
It would be great to pull the icons of linked shortcuts/executable files.

This would enhance link identification. Example Below:

<img width="264" alt="8YxuNSBxEg" src="https://github.com/mantasjasikenas/flow-launcher-shortcuts-plugin/assets/13816203/836d9997-e3b1-438b-a5b5-3f2969a96e41">

Great Plugin! Thanks.

**Comment by mantasjasikenas** [comment]
Thank you for the suggestion. I'll look into it in future.

**Comment by fischgeek** [comment]
Agreed. I initially thought you found some magic way to invoke my iOS shortcuts because of the icon you picked. I would advise against this and allow the user to set their own icon and/or do what @c0deZ3R0 suggested.
