### ISSUE TITLE
Add file URL support

### ISSUE THREAD

**Issue by willasm** [mantasjasikenas/flow-launcher-shortcuts-plugin#16]
It would be nice to have the file Url type. For example...

```json
  {
    "Type": "Url",
    "Path": "vscode://file/c:/programming/code/my_code/vscode/emerald-sky/",
    "Key": "vsc_emerald-sky"
  },
```

I can add this without error to the shortcuts config file, but nothing happens.

**Comment by EnigmaSolved** [comment]
I am purely just curious: What is the advantage of specifying the path in that way, vs just pointing it to a file/folder to open like normal?

**Comment by willasm** [comment]
Never mind as I got it working. Just had to change the type to "File" and it works. A little odd as that format is considered an URL, but it does work.
