### ISSUE TITLE
URL with search

### ISSUE THREAD

**Issue by DRYN07** [mantasjasikenas/flow-launcher-shortcuts-plugin#22]
Is it possible to use url shortcut like this and get search results: **https://www.google.com/search?q=%s** ?

**Comment by mantasjasikenas** [comment]
Yeah, it's possible. Add URL shortcut **www.google.com/search?q=${s}**

**Comment by DRYN07** [comment]
Thansk!

Although did I something wrong?

![image](https://github.com/user-attachments/assets/ace249ea-16e2-4ecc-8cd1-074a579612e6)

**Comment by mantasjasikenas** [comment]
![image](https://github.com/user-attachments/assets/92355079-9156-465f-8662-7ca7473c1fc2)
![image](https://github.com/user-attachments/assets/256d6ba0-d71e-4e78-afb8-5f355ab8e613)

I used the same shortcut on my machine, and everything works. Could you select that response and screenshot the error message? Also, check if you are using the latest version of the plugin.

**Comment by DRYN07** [comment]
Wow, strange... :/ 

I attach the error window and the error log. 

[error_window.txt](https://github.com/user-attachments/files/16278226/error_window.txt)
[log-2024-07-18.txt](https://github.com/user-attachments/files/16278228/log-2024-07-18.txt)
