### ISSUE TITLE
Define single key in a group

### ISSUE THREAD

**Issue by DRYN07** [mantasjasikenas/flow-launcher-shortcuts-plugin#23]
Is it possible to define single keys in a group?

For example lets say I have a group key to search on image sites (freepik, unsplash etc) but I also use these sites separately as well. Is it possible somehow or I must duplicate those for single usage?

```
[
  {
    "Type": "Group",
    "Shortcuts": 
    [
      {
        "Type": "Url",
        "Url": "freepik.com/search?q=${q}",
        /* can I set a key here? */
      },
      {
        "Type": "Url",
        "Url": "www.unsplash.com/search?q=${q}"
        /* can I set a key here? */
      }
    ],
    "Key": "search"
  }
]
```

**Comment by mantasjasikenas** [comment]
It will not allow invoking inside shortcuts if you set the key inside. The solution is to create separative shortcuts and add them to the group. Example of this:
```json
[
  {
    "Type": "Group",
    "Key": "search",
    "Keys": ["freepik", "unsplash"]
  },
  {
    "Type": "Url",
    "Url": "freepik.com/search?q=${q}",
    "Key": "freepik"
  },
  {
    "Type": "Url",
    "Url": "www.unsplash.com/search?q=${q}",
    "Key": "unsplash"
  }
]
```

**Comment by DRYN07** [comment]
Perfect, thanks :)

**Comment by DRYN07** [comment]
And is it possible to add more than one key to a shortcut?

**Comment by mantasjasikenas** [comment]
Currently, no, it's not possible to add more than one key to a shortcut. However, this functionality could be added relatively easily in future updates

**Comment by DRYN07** [comment]
If you have time in the future, I would appreciate it. Since there are already so many shortcuts to remember in daily work, I often encounter the issue of "here they write it this way, there they write it that way," and it would help a lot if more could be defined. By the way, I just want to note that the plugin is brilliant and deserves many more stars.
