### ISSUE TITLE
Feature Request: Add support for the QuickLook plugin to preview folders and files

### ISSUE THREAD

**Issue by nanoraptor** [mantasjasikenas/flow-launcher-shortcuts-plugin#29]
I've noticed that the latest update includes a preview feature within Flow Launcher. I have enabled the QuickLook Plugin, but any file or folder I preview through the shortcuts plugin only triggers the default FL preview. This might be an issue with the QL plugin. I'm not entirely certain. However, if it's feasible to integrate this feature, I would urge the developer to implement it as soon as possible. Also, the new version is quite impressive!

**Comment by mantasjasikenas** [comment]
Thanks for the feedback! I'll add QuickLook support in the next version.

**Comment by nanoraptor** [comment]
The QuickLook support is now implemented!!! Many thanks to @mantasjasikenas
