### ISSUE TITLE
Feature Request: Pull URL Icons/define custom path for Icons

### ISSUE THREAD

**Issue by c0deZ3R0** [mantasjasikenas/flow-launcher-shortcuts-plugin#33]
Would love for the URL icons to also be displayed:

![20240919_chrome](https://github.com/user-attachments/assets/de8b2418-a9f9-4aa8-a6b5-1b0589ad0616)

I assume it’s a lower priority, but it might be simpler to specify a path for .ico files, like this:

```
[
{
    "Type": "IconDirectory",
    "Directory" : "C:/icons/"
},
{
    "Type": "Url",
    "Url": "calculator:///",
    "Key": "calculator",
}
]
```
Icons labelled with the corresponding key, such as C:/icons/calculator.ico, could override the default.

Thanks for the updates! This plugin has made my life so much easier!

**Comment by mantasjasikenas** [comment]
Thank you for your feature request and feedback!

I’m considering adding a field in the Flow Launcher settings where users can specify a directory for icons, similar to how shortcuts and variables can currently be set. Would that solution work for you? I could also include a command to set the folder directly. Let me know what you think!

**Comment by c0deZ3R0** [comment]
Personally, I believe a single folder with icons, each directly associated with the relevant key, would be sufficient. I don’t see much value in using multiple directories; even a default directory within the plugin could work just fine.

That said, others may have different perspectives.

I’ve taken a look through your codebase and was thinking of submitting a pull request for this change. If you're open to it, please let me know how you'd like to proceed, and I’d be happy to give it a try.
