### ISSUE TITLE
Feature Request: Add Dynamic Variables (Vars) for URL Web Searches

### ISSUE THREAD

**Issue by itssource** [mantasjasikenas/flow-launcher-shortcuts-plugin#9]
Feature Request: "Dynamic Variables" (URL)

Description:
Instead of just static variables that are pre-defined before a call to _**q list ShortcutName ** [choose your URL], allow the user to select a URL from q list and then type in an optional search string, then perform the URL load.

Example URL:
https://www.google.com/search?q=**_coding+games_**&sca_esv=5854313 ("coding games" is the "Dynamic Variable (Var)".)

"coding games would be typed after the q list [choose an entry here] coding games.

Use-Case:
This would be helpful for forums, general search engines, etc. I want it for searching online help documents I use for development applications I use.

**Comment by mantasjasikenas** [comment]
Thank you for the suggestion.

Currently, you can override static variables when invoking a single shortcut. For example, you have defined shortcut `google` with URL **www.google.com/search?q=${q}**. Query command `q google -q coding games` would open **https://www.google.com/search?q=coding%20games**.

The next version will also support the command `q list -q coding games` . After typing this, select the desired shortcut from the list. Keep in mind that the shortcut should include the **q** param.
